const API=(window.MINEGUARD_API_URL||"").replace(/\/$/,"");let incidents=[],measurements=[];
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function request(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||"Request failed");return r.json()}
function empty(message){return `<div class="empty"><b>No records yet</b><p>${message}</p></div>`}
function rows(items,kind){if(!items.length)return empty(`Create the first ${kind} record to populate this area.`);return `<div class="table"><table><thead><tr><th>Date</th><th>Location</th><th>Type</th><th>Priority</th><th>Status</th></tr></thead><tbody>${items.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleDateString()}</td><td>${esc(x.location_name)}</td><td>${esc(x.report_type)}</td><td><span class="tag ${x.risk_level.toLowerCase()}">${x.risk_level}</span></td><td>${esc(x.status)}</td></tr>`).join("")}</tbody></table></div>`}
function render(){const d={incidents:incidents.length,open_cases:incidents.filter(x=>x.status!=="Closed").length,priority_cases:incidents.filter(x=>x.risk_level==="Priority").length,measurements_needing_review:measurements.filter(x=>x.needs_review).length};$("kpis").innerHTML=[["Reports",d.incidents],["Open cases",d.open_cases],["Priority",d.priority_cases],["Measurements for review",d.measurements_needing_review]].map(x=>`<article><span>${x[0]}</span><b>${x[1]}</b></article>`).join("");$("recent").innerHTML=rows(incidents.slice(0,6),"case");$("casesTable").innerHTML=incidents.length?incidents.map(x=>`<div class="case"><div><b>#${x.id} · ${esc(x.location_name)}</b><p>${esc(x.summary)}</p></div><label>Status<select data-case="${x.id}">${["Open","Under review","Action in progress","Closed"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></label></div>`).join(""):empty("Submitted reports will appear here for assignment and follow up.");$("measurements").innerHTML=measurements.length?`<div class="table"><table><thead><tr><th>Date</th><th>Point</th><th>Indicator</th><th>Result</th><th>Review</th></tr></thead><tbody>${measurements.map(x=>`<tr><td>${new Date(x.measured_at).toLocaleDateString()}</td><td>${esc(x.monitoring_point)}</td><td>${esc(x.indicator)}</td><td>${x.result_value} ${esc(x.unit)}</td><td>${x.needs_review?"Required":"Not flagged"}</td></tr>`).join("")}</tbody></table></div>`:empty("Saved environmental measurements will appear here.");$("reportSummary").innerHTML=`<h3>Current summary</h3><p>${d.incidents} reports · ${d.open_cases} open cases · ${measurements.length} measurements</p>`;document.querySelectorAll("[data-case]").forEach(el=>el.onchange=()=>updateCase(el.dataset.case,el.value))}
async function load(){try{[incidents,measurements]=await Promise.all([request("/api/incidents"),request("/api/measurements")]);$("apiStatus").textContent="System online";$("apiStatus").classList.add("online");render()}catch(e){$("apiStatus").textContent="API unavailable";$("recent").innerHTML=empty("The backend may be waking up. Please try again shortly.")}}
async function updateCase(id,status){const x=incidents.find(i=>i.id==id);await request(`/api/incidents/${id}`,{method:"PATCH",body:JSON.stringify({status,assignee:x.assignee||"Unassigned",action_note:x.action_note||""})});await load()}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-page],.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active");$("title").textContent=b.textContent});
$("incidentForm").onsubmit=async e=>{e.preventDefault();const val=id=>$(id).value;try{await request("/api/incidents",{method:"POST",body:JSON.stringify({occurred_at:new Date(val("occurredAt")).toISOString(),location_name:val("locationName"),report_type:val("reportType"),area:val("area"),severity:+val("severity"),recurrence:+val("recurrence"),control:val("control"),review_required:val("reviewRequired")==="true",latitude:val("latitude")?+val("latitude"):null,longitude:val("longitude")?+val("longitude"):null,summary:val("summary")})});e.target.reset();$("incidentMessage").textContent="Report saved";await load()}catch(x){$("incidentMessage").textContent=x.message}};
$("measurementForm").onsubmit=async e=>{e.preventDefault();const val=id=>$(id).value;try{await request("/api/measurements",{method:"POST",body:JSON.stringify({measured_at:new Date(val("measuredAt")+"T12:00:00").toISOString(),monitoring_point:val("monitoringPoint"),indicator:val("indicator"),result_value:+val("resultValue"),unit:val("unit"),review_threshold:val("reviewThreshold")?+val("reviewThreshold"):null,observation:val("observation")})});e.target.reset();$("measurementMessage").textContent="Measurement saved";await load()}catch(x){$("measurementMessage").textContent=x.message}};
$("downloadCsv").onclick=()=>{if(!incidents.length)return alert("There are no case records to export.");const h=["ID","Date","Location","Type","Area","Risk","Status","Summary"],lines=incidents.map(x=>[x.id,x.occurred_at,x.location_name,x.report_type,x.area,x.risk_level,x.status,x.summary].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","));const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([[h.join(","),...lines].join("\n")],{type:"text/csv"}));a.download="mineguard-case-register.csv";a.click()};
$("occurredAt").value=new Date().toISOString().slice(0,16);$("measuredAt").value=new Date().toISOString().slice(0,10);load();
